# permissions for end users to edit sites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: update-webpage
    app.kubernetes.io/managed-by: kustomize
  name: site-editor-role
rules:
- apiGroups:
  - page.biwbass.xyz
  resources:
  - sites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - page.biwbass.xyz
  resources:
  - sites/status
  verbs:
  - get
